name: Continuous-Integration

env:
  TERM: xterm

on:
  push:
    branches: [ master, development, regression-test ]

  pull_request:
    branches: [ master, development, regression-test ]

  workflow_dispatch:

jobs:
  build:

    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2

      - name: makefile check
        run: |
          make
          make clean
          make fclean
          make minishell
          make re
  test:

    runs-on: macos-11
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: unittests
        run: make test

      - name: regression test
        run: |
          brew install coreutils
          brew install readline
          pip3 install --upgrade norminette
          bash tests/minishell_tester.sh
