# This is a basic workflow to help you get started with Actions

name: CI

env:
  TERM: xterm

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, development, regression-test ]
  pull_request:
    branches: [ master, development, regression-test ]

  workflow_dispatch:

jobs:
  build:

    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2

      - name: makefile check
        run: |
          make
          make clean
          make fclean
          make minishell
          make re
  test:

    runs-on: macos-11
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: unittests
        run: make test

      - name: regression test
        run: |
          brew install coreutils
          bash tests/minishell_tester.sh
